name: CI Workflow for MariaDB Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: userInfo
          MYSQL_USER: users
          MYSQL_PASSWORD: 123456
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify MariaDB connection
        run: |
          # 等待 MariaDB 准备就绪
          while ! nc -z localhost 3306; do
            sleep 1;
          done
          echo "MariaDB is ready - $(date)"

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Create User
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_ROOT_PASS: 123456
        run: |
          # 使用 root 用户创建新用户
          mysql -h"$DB_HOST" -P"$DB_PORT" -uroot -p"$DB_ROOT_PASS" -e "
          CREATE USER 'root'@'localhost' IDENTIFIED BY '123456';
          GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
          FLUSH PRIVILEGES;
          "

      - name: Test Database
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_NAME: userInfo
          DB_USER: users
          DB_PASS: 123456

        # run: |
        #   mysqldump -u ${{ secrets.DB_USER }} -p'${{ secrets.DB_PASS }}' --socket=/run/mysql/mysql.sock userInfo > database.sql
        run: |
          # 创建一个表
          mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" <<EOF
          CREATE TABLE IF NOT EXISTS users (
              id INT AUTO_INCREMENT,
              name VARCHAR(100),
              PRIMARY KEY (id)
          );
          EOF

        #   # 插入数据
        #   mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" <<EOF
        #   INSERT INTO users (name) VALUES ('Alice'), ('Bob');
        #   EOF

        #   # 查询数据
        #   mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT * FROM users;"
