name: Deploy Database to GitHub

on:
  push:
    branches: [main] # 触发此工作流的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV

      - name: Create database dump
        run: |
          ssh 192.168.206.1 "mysqldump -u ${{ env.DB_USER }} -p'${{ env.DB_PASS }}' userInfo > database.sql"

      # - name: Commit and push changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add .
      #     git commit -m "Automatically backup database" || true
      #     git push origin main
