name: Backup Local MySQL Database

on:
  push:
    branches: [main] # 触发此工作流的分支

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Backup Database
        run: |
          mysqldump -u ${{ secrets.DB_USER }} -p'${{ secrets.DB_PASS }}' userInfo > database.sql
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

      - name: Add and Commit Changes
        run: |
          git config --local user.email "blww885@163.com"
          git config --local user.name "wwLoveWj"
          git add .
          git commit -m "Automatically backup database999" || true
          git push origin main
