name: MySQL Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Set up MySQL
        uses: mysql/setup-mysql@v2
        with:
          mysql-version: "5.7"
          mysql-port: 3306
          mysql-root-password: 123456

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # 运行测试的命令
          mysqldump -u ${{ secrets.DB_USER }} -p'${{ secrets.DB_PASS }}' userInfo > database.sql
